version: '3'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-boardroom-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Volumes for data persistence
volumes:
  postgres-data: