-- Migration for creating notifications table
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(500) NOT NULL,
    title VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    reservation_id BIGINT REFERENCES public.reservations(id),
    identifier VARCHAR(255) UNIQUE,
    tag VARCHAR(255) NOT NULL UNIQUE,
    activated BOOLEAN,
    archived BOOLEAN NOT NULL,
    deleted BOOLEAN,
    enabled BOOLEAN,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    occurred_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by BIGINT
);